# appveyor.yml reference : http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

skip_tags: true

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

clone_folder: c:\gopath\src\github.com\hashicorp\packer

install:
  - set GO111MODULE=off
  - echo %Path%
  - go version
  - go env
  - go get github.com/mitchellh/gox
  - go get golang.org/x/tools/cmd/stringer

build_script:
  - git rev-parse HEAD
 # go test $(go list ./... | grep -v vendor)
  - ps: |
      go.exe test -timeout=2m (go.exe list ./... `
      |? { -not $_.Contains('/vendor/') } `
      |? { $_ -ne 'github.com/hashicorp/packer/builder/parallels/common' } `
      |? { $_ -ne 'github.com/hashicorp/packer/provisioner/ansible' })
  - go build -o bin/packer.exe .
  - ps: (git describe) -replace '^v' -replace '-[0-9]+-','-' | Out-File bin/VERSION -Encoding ASCII

test: off

deploy: off

artifacts:
- path: 'bin\*'
